### [The Complete Poems of Francis Ledwidge](https://en.wikisource.org/wiki/The_Complete_Poems_of_Francis_Ledwidge) Music Pack

#### Usage: 

For all players:

`/mvolume` <volume>  Set your individual music volume or disable background music (/mvolume 0). Saved across server restarts. <br>
`/music_list`: list available music <br>
With mpd privilege: <br>
`/music_play` <id>: play a song <br>
`/music_stop`: stop the current song. Unless /mpd_play or /mpd_next are invoked, no more music is played <br>
`/music_next` [time]: Play the next song after [time] seconds, immediately if omitted. <br>
## Votes: <br>
This mod integrates with the [vote](https://content.minetest.net/metapackages/vote/) mod by rubenwardy  <br>
`/vote_music_next` - vote to start next song <br>
`/vote_music_play` <id> - Vote to play certain sing <br>
	
	
## License
Credits and Ackowledgements <br>
[balabolka](http://www.cross-plus-a.com/balabolka.htm) Provide music production software.
	
#### License of source code:LGPL-2.1-only
This mod is a fork of [mpd](https://content.minetest.net/packages/orwell/mpd/), which itself is a fork

#### License of music:CC BY-SA 3.0
I use https://en.wikisource.org/wiki/Universal_Declaration_of_Human_Rights to generate the ogg
	
#### License of Text:CC BY-SA 3.0
This work was published before January 1, 1927, and is in the public domain worldwide because the author died at least 100 years ago.[The Complete Poems of Francis Ledwidge](https://en.wikisource.org/wiki/The_Complete_Poems_of_Francis_Ledwidge)
